CREATE TABLE EMPLOYEES (
    ID INT AUTO_INCREMENT,
    FIRST_NAME VARCHAR(50) NOT NULL,
    MIDDLE_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50) NOT NULL,
    AGE INT NOT NULL,
    CURRENT_STATUS VARCHAR(50) NOT NULL DEFAULT 'EMPLOYED',
    PRIMARY KEY (ID)
);


INSERT INTO EMPLOYEES(FIRST_NAME,LAST_NAME,AGE)
VALUES
('ASWIN','SHARON',21),
('JOHN','DOE',22)
;
